controllers:
    resource: ../src/Controller/
    type: attribute
detailpagina:
    path: /detailpagina/{id}
    controller: App\Controller\HomepageController::show
medewerker_wijziging:
    path: '/medewerker/wijziging'
    controller: 'App\Controller\HomepageController::saveBezoek'
    methods: ['POST']
