controllers:
    resource: ../src/Controller/
    type: attribute
detailpagina:
    path: /detailpagina/{id}
    controller: App\Controller\HomepageController::show
bezoek_save:
    path: '/save'
    controller: 'App\Controller\HomepageController::saveBezoek'
    methods: ['POST']
