controllers:
    resource: ../src/Controller/
    type: attribute
detailpagina:
    path: /detailpagina/{id}
    controller: App\Controller\PageController::show
api_save:
    path: '/save'
    controller: 'App\Controller\apiController::saveBezoek'
    methods: ['POST']
